package org.freemaps.datum;

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.Settings;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

// Generated by scripts/ensure-storage-plugin.js - safe to regenerate,
// don't hand-edit (changes will be overwritten on the next sync).
//
// MANAGE_EXTERNAL_STORAGE ("All files access") can only be granted by
// sending the user to a specific system Settings screen - there's no
// normal runtime permission dialog for it. Once granted, though,
// @capacitor/filesystem's Directory.EXTERNAL_STORAGE starts working with
// real file paths again (it uses plain java.io.File under the hood,
// which is exactly what this permission restores access to).
@CapacitorPlugin(name = "AllFilesAccess")
public class AllFilesAccessPlugin extends Plugin {

    @PluginMethod
    public void isGranted(PluginCall call) {
        JSObject result = new JSObject();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            result.put("granted", Environment.isExternalStorageManager());
        } else {
            result.put("granted", true); // permission model doesn't exist before Android 11
        }
        call.resolve(result);
    }

    @PluginMethod
    public void requestAccess(PluginCall call) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            try {
                Intent intent = new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION);
                intent.setData(Uri.parse("package:" + getContext().getPackageName()));
                getActivity().startActivity(intent);
            } catch (Exception e) {
                getActivity().startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));
            }
        }
        call.resolve();
    }
}
