package org.freemaps.datum;

import android.content.Context;
import android.hardware.GeomagneticField;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

// Generated by scripts/ensure-compass-plugin.js - safe to regenerate,
// don't hand-edit (changes will be overwritten on the next sync).
//
// Streams a "headingUpdate" event ({heading, accuracy}) built from the
// device's TYPE_ROTATION_VECTOR sensor - Android's own fused, drift-
// corrected accel+gyro+magnetometer orientation - true-north-corrected
// via GeomagneticField using whatever location was last passed in through
// updateLocation(), and lightly smoothed to reduce residual jitter.
@CapacitorPlugin(name = "CompassSensor")
public class CompassSensorPlugin extends Plugin implements SensorEventListener {

    // Adaptive smoothing. A single fixed alpha has to be a compromise
    // between two opposite jobs: suppressing the constant few-degree
    // jitter of a magnetometer at rest, and following a real turn without
    // visible lag. Scaling alpha by how large the change is lets it do
    // both - tiny changes are treated as noise and damped hard, large
    // ones are treated as genuine movement and followed quickly.
    //
    // These values are tuned for SENSOR_DELAY_UI (~60ms). An EMA's time
    // constant depends on sample rate, so they would be far too heavy at
    // the ~20ms of SENSOR_DELAY_GAME - if the rate below is ever changed,
    // these have to change with it.
    private static final double SMOOTHING_ALPHA_MIN = 0.20; // jitter: heavy damping
    private static final double SMOOTHING_ALPHA_MAX = 0.65; // real turn: follow closely
    private static final double SMOOTHING_NOISE_DEG = 2.0;  // at or below this, assume noise
    private static final double SMOOTHING_TURN_DEG = 25.0;  // at or above this, assume a real turn

    private SensorManager sensorManager;
    private Sensor rotationVectorSensor;
    private boolean listening = false;

    private Double lastLat = null;
    private Double lastLng = null;
    private Double lastAlt = null;

    private Double smoothedHeading = null;
    private int lastAccuracy = SensorManager.SENSOR_STATUS_UNRELIABLE;

    @Override
    public void load() {
        sensorManager = (SensorManager) getContext().getSystemService(Context.SENSOR_SERVICE);
        rotationVectorSensor = sensorManager.getDefaultSensor(Sensor.TYPE_ROTATION_VECTOR);
    }

    @PluginMethod
    public void isAvailable(PluginCall call) {
        JSObject result = new JSObject();
        result.put("available", rotationVectorSensor != null);
        call.resolve(result);
    }

    @PluginMethod
    public void start(PluginCall call) {
        if (rotationVectorSensor != null && !listening) {
            sensorManager.registerListener(this, rotationVectorSensor, SensorManager.SENSOR_DELAY_UI);
            listening = true;
        }
        call.resolve();
    }

    @PluginMethod
    public void stop(PluginCall call) {
        if (listening) {
            sensorManager.unregisterListener(this);
            listening = false;
            smoothedHeading = null; // don't let a stale value carry into the next session
        }
        call.resolve();
    }

    @PluginMethod
    public void updateLocation(PluginCall call) {
        lastLat = call.getDouble("latitude");
        lastLng = call.getDouble("longitude");
        lastAlt = call.getDouble("altitude", 0.0);
        call.resolve();
    }

    @Override
    protected void handleOnPause() {
        // Stop listening while backgrounded: the rotation vector sensor
        // otherwise keeps firing at SENSOR_DELAY_UI the whole time the
        // phone is in a pocket, which burns battery for readings nothing
        // is displaying. `listening` deliberately stays true so resume
        // knows to re-register.
        if (listening) sensorManager.unregisterListener(this);
    }

    @Override
    protected void handleOnResume() {
        if (listening && rotationVectorSensor != null) {
            smoothedHeading = null; // don't blend the first new reading against a stale pre-pause value
            sensorManager.registerListener(this, rotationVectorSensor, SensorManager.SENSOR_DELAY_UI);
        }
    }

    @Override
    public void onSensorChanged(SensorEvent event) {
        if (event.sensor.getType() != Sensor.TYPE_ROTATION_VECTOR) return;

        float[] rotationMatrix = new float[9];
        SensorManager.getRotationMatrixFromVector(rotationMatrix, event.values);
        float[] orientation = new float[3];
        SensorManager.getOrientation(rotationMatrix, orientation);
        double magneticHeading = Math.toDegrees(orientation[0]);
        magneticHeading = ((magneticHeading % 360) + 360) % 360;

        double trueHeading = magneticHeading;
        if (lastLat != null && lastLng != null) {
            GeomagneticField field = new GeomagneticField(
                lastLat.floatValue(),
                lastLng.floatValue(),
                lastAlt != null ? lastAlt.floatValue() : 0f,
                System.currentTimeMillis()
            );
            trueHeading = ((magneticHeading + field.getDeclination()) % 360 + 360) % 360;
        }

        smoothedHeading = smooth(trueHeading);

        JSObject data = new JSObject();
        data.put("heading", smoothedHeading);
        data.put("accuracy", accuracyLabel(lastAccuracy));
        notifyListeners("headingUpdate", data);
    }

    @Override
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
        lastAccuracy = accuracy;
    }

    // Circular exponential moving average - a plain EMA breaks across the
    // 0/360 seam (naively averaging 359 and 1 gives 180, not 0), so this
    // moves toward the new reading by the shortest angular path instead.
    private double smooth(double newHeading) {
        if (smoothedHeading == null) return newHeading;
        double delta = newHeading - smoothedHeading;
        delta = ((delta + 180) % 360 + 360) % 360 - 180;

        double magnitude = Math.abs(delta);
        double alpha;
        if (magnitude <= SMOOTHING_NOISE_DEG) {
            alpha = SMOOTHING_ALPHA_MIN;
        } else if (magnitude >= SMOOTHING_TURN_DEG) {
            alpha = SMOOTHING_ALPHA_MAX;
        } else {
            // Linear ramp between the two, so there's no visible step in
            // responsiveness as a movement grows.
            double t = (magnitude - SMOOTHING_NOISE_DEG) / (SMOOTHING_TURN_DEG - SMOOTHING_NOISE_DEG);
            alpha = SMOOTHING_ALPHA_MIN + t * (SMOOTHING_ALPHA_MAX - SMOOTHING_ALPHA_MIN);
        }
        return ((smoothedHeading + delta * alpha) % 360 + 360) % 360;
    }

    private String accuracyLabel(int accuracy) {
        switch (accuracy) {
            case SensorManager.SENSOR_STATUS_ACCURACY_HIGH: return "high";
            case SensorManager.SENSOR_STATUS_ACCURACY_MEDIUM: return "medium";
            case SensorManager.SENSOR_STATUS_ACCURACY_LOW: return "low";
            default: return "unreliable";
        }
    }
}
